/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:5b2481b9-25ac-486c-a6e6-883f11dd723f",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_55uL3RsaO",
    "aws_user_pools_web_client_id": "ppnrnod71nof7uvus5rj1jguj",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    // "aws_cognito_mfa_types": [
    //     "SMS"
    // ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
